function Terms() {
  return (
    <div className="min-h-screen bg-white py-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 mb-4">Terms of Service</h1>
        <p className="text-gray-600 mb-8">Last updated: February 12, 2026</p>

        <div className="prose prose-lg max-w-none">
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-600 mb-4">
              By accessing and using ClipForge AI ("Service"), you accept and agree to be bound by the terms 
              and provision of this agreement. If you do not agree to these Terms of Service, please do not 
              use the Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Description of Service</h2>
            <p className="text-gray-600 mb-4">
              ClipForge AI provides AI-powered video editing and clipping services that allow users to:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2 mb-4">
              <li>Upload or import videos from YouTube</li>
              <li>Generate short-form clips using AI emotion detection</li>
              <li>Edit and customize video clips</li>
              <li>Export and publish content to various platforms</li>
              <li>Schedule and manage social media posts</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">3. User Accounts</h2>
            <p className="text-gray-600 mb-4">
              To use certain features of the Service, you must register for an account. You agree to:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2 mb-4">
              <li>Provide accurate, current, and complete information</li>
              <li>Maintain and update your information to keep it accurate</li>
              <li>Maintain the security of your password</li>
              <li>Accept responsibility for all activities under your account</li>
              <li>Notify us immediately of any unauthorized use</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Content Ownership and Rights</h2>
            <p className="text-gray-600 mb-4">
              <strong>Your Content:</strong> You retain all rights to the content you upload to ClipForge AI. 
              By uploading content, you grant us a limited license to process, store, and display your content 
              solely for the purpose of providing the Service.
            </p>
            <p className="text-gray-600 mb-4">
              <strong>Generated Content:</strong> You own all clips and edited content generated by our AI. 
              We do not claim any ownership rights to your generated content.
            </p>
            <p className="text-gray-600 mb-4">
              <strong>Third-Party Content:</strong> You are responsible for ensuring you have the necessary 
              rights to any content you upload or process through our Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Acceptable Use Policy</h2>
            <p className="text-gray-600 mb-4">You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2 mb-4">
              <li>Upload or process content that infringes on intellectual property rights</li>
              <li>Create or distribute illegal, harmful, or offensive content</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with or disrupt the Service</li>
              <li>Use the Service for any automated or bulk processing without permission</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Subscription and Payment</h2>
            <p className="text-gray-600 mb-4">
              <strong>Free Plan:</strong> We offer a limited free plan with basic features.
            </p>
            <p className="text-gray-600 mb-4">
              <strong>Paid Plans:</strong> Paid subscriptions are billed monthly or annually. You authorize 
              us to charge your payment method for all fees incurred.
            </p>
            <p className="text-gray-600 mb-4">
              <strong>Cancellation:</strong> You may cancel your subscription at any time. Cancellations 
              take effect at the end of the current billing period.
            </p>
            <p className="text-gray-600 mb-4">
              <strong>Refunds:</strong> We offer a 14-day money-back guarantee on all paid plans.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Service Availability</h2>
            <p className="text-gray-600 mb-4">
              We strive to provide reliable service but do not guarantee uninterrupted access. We may 
              modify, suspend, or discontinue any aspect of the Service at any time with reasonable notice.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Limitation of Liability</h2>
            <p className="text-gray-600 mb-4">
              To the maximum extent permitted by law, ClipForge AI shall not be liable for any indirect, 
              incidental, special, consequential, or punitive damages, or any loss of profits or revenues, 
              whether incurred directly or indirectly.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Indemnification</h2>
            <p className="text-gray-600 mb-4">
              You agree to indemnify and hold ClipForge AI harmless from any claims, damages, losses, 
              liabilities, and expenses arising from your use of the Service or violation of these Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">10. Changes to Terms</h2>
            <p className="text-gray-600 mb-4">
              We reserve the right to modify these Terms at any time. We will notify users of significant 
              changes via email or through the Service. Continued use after changes constitutes acceptance 
              of the modified Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">11. Termination</h2>
            <p className="text-gray-600 mb-4">
              We may terminate or suspend your account and access to the Service immediately, without prior 
              notice, for any breach of these Terms or for any other reason at our sole discretion.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">12. Governing Law</h2>
            <p className="text-gray-600 mb-4">
              These Terms shall be governed by and construed in accordance with the laws of the State of 
              California, United States, without regard to its conflict of law provisions.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">13. Contact Information</h2>
            <p className="text-gray-600 mb-4">
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="text-gray-600">
              Email: legal@clipforge.ai<br />
              Address: 123 AI Street, San Francisco, CA 94102
            </p>
          </section>
        </div>

        <div className="mt-12 p-6 bg-purple-50 rounded-xl">
          <p className="text-sm text-gray-600">
            By using ClipForge AI, you acknowledge that you have read, understood, and agree to be bound 
            by these Terms of Service.
          </p>
        </div>
      </div>
    </div>
  );
}

export default Terms;
